#############################################################################################################################################################################
# PreRequisite: Download the libraries

### 1. Pandas: It is a super-powered spreadsheet tool for Python, perfect for organizing, cleaning, and analyzing complex data tables efficiently.

### 2. NumPy: It is for scientific computing in Python, providing extremely fast ways to handle large lists and tables of numbers (arrays) for mathematical calculations.

### 3. yfinance: It is a simple data downloader that allows to fetch real, up-to-date historical stock market prices and volume data directly from Yahoo! Finance. 

#############################################################################################################################################################################

In [1]:
!pip install pandas
!pip install numpy
!pip install yfinance

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.1.1)
Requirement already satisfied: yfinance in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.1.1)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/shaun/Library/Python/3.12/lib/python/site-packages (from yfinance) (4.3.2)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (4.13.4)
Requirement already satisfied: curl_cffi>=0.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (6.32.1)
Requirement already satisfied: websockets>=13.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: cffi>=1.12.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /Users/shaun/Library/Python/3.12/lib/python/site-packages (from curl_cffi>=0.7->yfinance) (2024.8.30)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.2.3)

#########################################################################################
# STEP 1: Load data from online source (Yahoo! Finance)
#########################################################################################

In [6]:
import pandas as pd
import numpy as np
import yfinance as yf

Collecting yfinance
  Using cached yfinance-0.2.66-py2.py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: pandas>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yfinance) (1.25.1)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.12.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: platformdirs>=2.0.0 in /Users/shaun/Library/Python/3.11/lib/python/site-packages (from yfinance) (3.9.1)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yfinance) (2023.3)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.6-py311-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Using cached peewee-3.18.2.tar.gz (949 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yfinance) (4.12.2)
Collecting curl_cffi>=0.7 (from yfinance)
  Using cached curl_cffi-0.13.0-cp39-abi3-macosx_10_9_x86_64.whl.metadata (13 kB)
Requirement already satisfied: protobuf>=3.19.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yfinance) (4.21.12)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Collecting cffi>=1.12.0 (from curl_cffi>=0.7->yfinance)
  Downloading cffi-2.0.0-cp311-cp311-macosx_10_13_x86_64.whl.metadata (2.6 kB)
Collecting certifi>=2024.2.2 (from curl_cffi>=0.7->yfinance)
  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Collecting pycparser (from cffi>=1.12.0->curl_cffi>=0.7->yfinance)
  Downloading pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests>=2.31->yfinance) (1.26.16)
Using cached yfinance-0.2.66-py2.py3-none-any.whl (123 kB)
Using cached curl_cffi-0.13.0-cp39-abi3-macosx_10_9_x86_64.whl (5.7 MB)
Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
Downloading cffi-2.0.0-cp311-cp311-macosx_10_13_x86_64.whl (184 kB)
Downloading frozendict-2.4.6-py311-none-any.whl (16 kB)
Downloading websockets-15.0.1-cp311-cp311-macosx_10_9_x86_64.whl (173 kB)
Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Building wheels for collected packages: multitasking, peewee
  Building wheel for multitasking (pyproject.toml) ... done
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15636 sha256=8ff8fda8f5df4e9a8c57d3455bd6581c000d92632ebac90b1ce1b03d7eb98033
  Stored in directory: /Users/shaun/Library/Caches/pip/wheels/42/d6/84/bf57a755f4569494cd00de4bb46ef064874823f4d19c82e960
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.18.2-cp311-cp311-macosx_10_9_universal2.whl size=416761 sha256=2c9c67f4ceee79daddd72dd97ea99242501af6a3f5c1ed47fd672830da3a1ed4
  Stored in directory: /Users/shaun/Library/Caches/pip/wheels/28/84/61/758d1bd7b9c9d700158c8642a8aff2a9bf2e1ae69641c40784
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, pycparser, frozendict, certifi, cffi, curl_cffi, yfinance
  Attempting uninstall: certifi[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/9 [websockets]
    Found existing installation: certifi 2023.7.22━━━━━━━━━━━━━━━━ 5/9 [certifi]
    Uninstalling certifi-2023.7.22:╺━━━━━━━━━━━━━━━━━ 5/9 [certifi]
      Successfully uninstalled certifi-2023.7.22━━━━━━━━━━━━━━ 5/9 [certifi]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [yfinance]8/9 [yfinance]]
Successfully installed certifi-2025.10.5 cffi-2.0.0 curl_cffi-0.13.0 frozendict-2.4.6 multitasking-0.0.12 peewee-3.18.2 pycparser-2.23 websockets-15.0.1 yfinance-0.2.66

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip3.11 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Collecting Google data from 2024-10-01 to 2025-10-01. (Date format: Year-Month-Date)
TICKER = "GOOGL"
START_DATE = "2024-10-01"
END_DATE = "2025-10-01"

# Business Day : A business day is any day, excluding weekends and official public holidays,
# when major financial markets and banks are open for business and transactions

try:
    # Download data
    data = yf.download(TICKER, start=START_DATE, end=END_DATE)

except Exception as e:
    print(f"Error downloading data: {e}")
    print("Please ensure you have 'yfinance' installed (pip install yfinance).")
    exit()

/var/folders/s3/qnjcsd9n5b529p_ckj5h51jh0000gn/T/ipykernel_34743/1534914217.py:11: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(TICKER, start=START_DATE, end=END_DATE)
[*********************100%***********************]  1 of 1 completed

In [184]:
# Provide the type of the dataset
type(data)

pandas.core.frame.DataFrame

In [185]:
# List all the columns of the dataset
data.columns

MultiIndex([( 'Close', 'GOOGL'),
            (  'High', 'GOOGL'),
            (   'Low', 'GOOGL'),
            (  'Open', 'GOOGL'),
            ('Volume', 'GOOGL')],
           names=['Price', 'Ticker'])

In [186]:
# Provide the size of dataset 250 rows and 2 columns
data.shape

(250, 5)

In [187]:
# View data top 7 rows, bydefault head shows first 5 rows
data.head(7)

Price            Close        High         Low        Open    Volume
Ticker           GOOGL       GOOGL       GOOGL       GOOGL     GOOGL
Date
2024-10-01  166.256821  168.417291  163.857398  166.953744  28338100
2024-10-02  165.131775  166.784490  164.006731  165.689314  17760200
2024-10-03  165.131775  165.908349  163.200290  163.688144  15073100
2024-10-04  166.326492  167.491353  164.753428  167.322102  19047400
2024-10-07  162.264404  167.740256  162.035418  166.983598  22463100
2024-10-08  163.658264  164.006718  162.154884  163.220194  23072700
2024-10-09  161.149323  164.116234  159.038636  162.732338  31181800

In [188]:
# View data bottom 7 rows
data.tail(7)

Price            Close        High         Low        Open    Volume
Ticker           GOOGL       GOOGL       GOOGL       GOOGL     GOOGL
Date
2025-09-22  252.529999  255.779999  250.300003  254.429993  32290500
2025-09-23  251.660004  254.360001  250.479996  253.039993  26628000
2025-09-24  247.139999  252.350006  246.440002  251.660004  28201000
2025-09-25  245.789993  246.490005  240.740005  244.399994  31020400
2025-09-26  246.539993  249.419998  245.970001  247.070007  18503200
2025-09-29  244.050003  251.149994  242.770004  247.850006  32505800
2025-09-30  243.100006  243.289993  239.250000  242.809998  34724300

In [189]:
# Type of each column
data.dtypes

Price   Ticker
Close   GOOGL     float64
High    GOOGL     float64
Low     GOOGL     float64
Open    GOOGL     float64
Volume  GOOGL       int64
dtype: object

In [190]:
# Select only the columns needed for quantitative analysis
data = data[["Close", "Volume"]]

In [191]:
data.head()

Price            Close    Volume
Ticker           GOOGL     GOOGL
Date
2024-10-01  166.256821  28338100
2024-10-02  165.131775  17760200
2024-10-03  165.131775  15073100
2024-10-04  166.326492  19047400
2024-10-07  162.264404  22463100

In [192]:
print(f"\nInitial Missing Value Count:\n{data.isnull().sum()}")

Initial Missing Value Count:
Price   Ticker
Close   GOOGL     0
Volume  GOOGL     0
dtype: int64

In [193]:
# iloc is used to slice the data
# dataframe.iloc[row, column]
# collected 10 rows which be used to add impurities
data.iloc[10:20]

Price            Close    Volume
Ticker           GOOGL     GOOGL
Date
2024-10-15  164.733536  20247200
2024-10-16  164.434845  16406000
2024-10-17  162.214615  21453400
2024-10-18  162.702484  19757700
2024-10-21  163.349640  20946500
2024-10-22  164.414932  16568100
2024-10-23  162.065292  18280500
2024-10-24  162.005554  22412500
2024-10-25  164.544357  19828900
2024-10-28  165.987991  32138600

In [194]:
# Introducing some artificial missing values and an outlier for demonstration
# This simulates common data issues even with real feeds
data.iloc[10:20, data.columns.get_loc("Close")] = np.nan

In [195]:
# Data got impuried
data.iloc[10:20]

Price      Close    Volume
Ticker     GOOGL     GOOGL
Date
2024-10-15   NaN  20247200
2024-10-16   NaN  16406000
2024-10-17   NaN  21453400
2024-10-18   NaN  19757700
2024-10-21   NaN  20946500
2024-10-22   NaN  16568100
2024-10-23   NaN  18280500
2024-10-24   NaN  22412500
2024-10-25   NaN  19828900
2024-10-28   NaN  32138600

In [196]:
# Row 20 without an outlier impurity
data.iloc[20]

Price   Ticker
Close   GOOGL     1.689350e+02
Volume  GOOGL     4.216900e+07
Name: 2024-10-29 00:00:00, dtype: float64

In [197]:
# Introducing an outlier in Volume
outlier_idx = 20  # chossing row 20
data.iloc[outlier_idx, data.columns.get_loc("Volume")] = (
    data["Volume"].max() * 5
)  # Extreme volume spike

In [198]:
# Row 20 after adding an outlier impurity
data.iloc[20]

Price   Ticker
Close   GOOGL     1.689350e+02
Volume  GOOGL     6.374505e+08
Name: 2024-10-29 00:00:00, dtype: float64

In [199]:
data.iloc[20, data.columns.get_loc("Volume")]

Price   Ticker
Volume  GOOGL     637450500
Name: 2024-10-29 00:00:00, dtype: int64

###################################################################################
# STEP 2: Data Cleaning (Handling NaNs and Outliers)
###################################################################################

#### What is Linear Interpolation?
#### Linear interpolation in time-series analysis is a method used to estimate missing data points by drawing a straight line between the nearest two known data points. This approach helps maintain trend continuity by assuming a constant rate of change between the known, adjacent observations.

![Image](Linear_Interpolation_Formula.png)

In [200]:
# Handling Missing Close Values (NaNs)
# Strategy: Use linear interpolation to maintain the time-series trend continuity.
data["Close"] = data["Close"].interpolate(method="linear")

In [201]:
# Close columns NaNs handled using Linear Interpolation.
data.iloc[10:20]

Price            Close    Volume
Ticker           GOOGL     GOOGL
Date
2024-10-15  164.662924  20247200
2024-10-16  165.090130  16406000
2024-10-17  165.517335  21453400
2024-10-18  165.944541  19757700
2024-10-21  166.371747  20946500
2024-10-22  166.798953  16568100
2024-10-23  167.226159  18280500
2024-10-24  167.653365  22412500
2024-10-25  168.080571  19828900
2024-10-28  168.507776  32138600

### What is Interquartile Range?
#### The Interquartile Range (IQR) method is a statistical technique used to measure the spread of the middle half of a dataset and to identify outliers (extreme values).

![Image](box_plot.png)

In [202]:
# Handling Volume Outliers
# Strategy: Using the IQR method (1.5 * IQR (Lower Fence (Lower Outlier Threshold)) or 3.0 * IQR (Upper Fence (Upper Outlier Threshold))) to cap extreme values.
Q1 = data["Volume"].quantile(0.25)
Q3 = data["Volume"].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 3.0 * IQR

# Limit the volume values
data["Volume"] = data["Volume"].clip(upper=upper_bound, axis=1)


print(f"Volume at Outlier Index (Row 20) after capping: {data['Volume'].iloc[20]}")

Volume at Outlier Index (Row 20) after capping: Ticker
GOOGL    86513550
Name: 2024-10-29 00:00:00, dtype: int64

# Question :  Add an outlier on the lower bound and see how the lower bound behaves

#########################################################################################
# STEP 3: Feature Engineering (Creating Quant Metrics)
#########################################################################################

#### What is log return?
#### The log return (continuously compounded return) is a way of calculating the rate of return on an investment by taking the natural logarithm of the price ratio. It is a fundamental concept in financial modeling and quantitative finance.

In [203]:
# Creating a new column Log_Return
# Log Returns (Measure of Price Change/Volatility)
data["Log_Return"] = np.log(data["Close"] / data["Close"].shift(1))

In [204]:
data.columns

MultiIndex([(     'Close', 'GOOGL'),
            (    'Volume', 'GOOGL'),
            ('Log_Return',      '')],
           names=['Price', 'Ticker'])

In [205]:
# Volatility Feature (10-Day Rolling Standard Deviation of Returns)
# Creates a measure of risk over the last 10 days.
data["Vol_10D"] = data["Log_Return"].rolling(window=10).std()

In [206]:
# Momentum Feature (20-Day Simple Moving Average)
# Measures the longer-term trend.
data["SMA_20D"] = data["Close"].rolling(window=20).mean()

In [207]:
# Feature Interaction: Price/Volume Ratio
data["PV_Ratio"] = data["Close"] / data["Volume"]

In [208]:
# Categorical Signal
# Simple 'Up' or 'Down' signal based on previous day's return
data["Trading_Signal"] = np.where(data["Log_Return"].shift(1) > 0, "Up", "Down")

########################################################################################################
# STEP 4: Scaling and Encoding (Standardization and One Hot Encoding)
########################################################################################################

In [209]:
# All continuous features that need to be scaled
CONTINUOUS_FEATURES = [
    "Close",
    "Volume",
    "Log_Return",
    "Vol_10D",
    "SMA_20D",
    "PV_Ratio",
]

#### What is Z-score?
#### Z-score normalization (standardization), is a statistical method that rescales data so that it has a mean (μ) of 0 and a standard deviation (σ) of 1.

In [210]:
# Standardization (Z-score Normalization)
# We calculate mu and sigma for each column independently.
for col in CONTINUOUS_FEATURES:
    # 1. Calculate statistics (column-wise mean and std dev)
    mu = data[col].mean()
    sigma = data[col].std()

    # 2. Apply Z-score formula: z = (x - mu) / sigma
    data[f"{col}_Z"] = (data[col] - mu) / sigma

In [211]:
data.columns

MultiIndex([(         'Close', 'GOOGL'),
            (        'Volume', 'GOOGL'),
            (    'Log_Return',      ''),
            (       'Vol_10D',      ''),
            (       'SMA_20D',      ''),
            (      'PV_Ratio',      ''),
            ('Trading_Signal',      ''),
            (       'Close_Z',      ''),
            (      'Volume_Z',      ''),
            (  'Log_Return_Z',      ''),
            (     'Vol_10D_Z',      ''),
            (     'SMA_20D_Z',      ''),
            (    'PV_Ratio_Z',      '')],
           names=['Price', 'Ticker'])

In [212]:
data.head()

Price,Close,Volume,Log_Return,Vol_10D,SMA_20D,PV_Ratio,Trading_Signal,Close_Z,Volume_Z,Log_Return_Z,Vol_10D_Z,SMA_20D_Z,PV_Ratio_Z
Ticker,GOOGL,GOOGL,,,,,,,,,,,
Date,,,,,,,,,,,,,
2024-10-01,166.256821,28338100,NaN,NaN,NaN,0.000006,Down,-0.679042,-0.387948,NaN,NaN,NaN,-0.150121
2024-10-02,165.131775,17760200,-0.006790,NaN,NaN,0.000009,Down,-0.726853,-1.106996,-0.413174,NaN,NaN,1.222808
2024-10-03,165.131775,15073100,0.000000,NaN,NaN,0.000011,Down,-0.726853,-1.289655,-0.075813,NaN,NaN,1.886088
2024-10-04,166.326492,19047400,0.007209,NaN,NaN,0.000009,Down,-0.676081,-1.019496,0.282364,NaN,NaN,0.996472
2024-10-07,162.264404,22463100,-0.024726,NaN,NaN,0.000007,Up,-0.848707,-0.787309,-1.304316,NaN,NaN,0.392774

In [213]:
# One-Hot Encoding for the Trading Signal
# Convert the 'Up'/'Down' categorical feature into binary columns.
# drop_first=True prevents multicollinearity by making 'Down' the implied state
# when 'Signal_Up' is 0.
signal_dummies = pd.get_dummies(
    data[("Trading_Signal", "")], prefix="Signal", drop_first=True
)
data["Signal_Up"] = signal_dummies["Signal_Up"]
data.drop(("Trading_Signal", ""), axis=1, inplace=True)

In [214]:
data.head()

Price,Close,Volume,Log_Return,Vol_10D,SMA_20D,PV_Ratio,Close_Z,Volume_Z,Log_Return_Z,Vol_10D_Z,SMA_20D_Z,PV_Ratio_Z,Signal_Up
Ticker,GOOGL,GOOGL,,,,,,,,,,,
Date,,,,,,,,,,,,,
2024-10-01,166.256821,28338100,NaN,NaN,NaN,0.000006,-0.679042,-0.387948,NaN,NaN,NaN,-0.150121,False
2024-10-02,165.131775,17760200,-0.006790,NaN,NaN,0.000009,-0.726853,-1.106996,-0.413174,NaN,NaN,1.222808,False
2024-10-03,165.131775,15073100,0.000000,NaN,NaN,0.000011,-0.726853,-1.289655,-0.075813,NaN,NaN,1.886088,False
2024-10-04,166.326492,19047400,0.007209,NaN,NaN,0.000009,-0.676081,-1.019496,0.282364,NaN,NaN,0.996472,False
2024-10-07,162.264404,22463100,-0.024726,NaN,NaN,0.000007,-0.848707,-0.787309,-1.304316,NaN,NaN,0.392774,True

################################################################################
# STEP 5: Final Data Cleanup and Inspection
################################################################################

In [215]:
# Drop any rows that still contain NaNs (created by the rolling windows at the start).
data.dropna(inplace=True)
print(f"Final Cleaned, Engineered, Scaled, and Encoded Data Shape: {data.shape}")

Final Cleaned, Engineered, Scaled, and Encoded Data Shape: (231, 13)

In [ ]:
data[""]

MultiIndex([(       'Close', 'GOOGL'),
            (      'Volume', 'GOOGL'),
            (  'Log_Return',      ''),
            (     'Vol_10D',      ''),
            (     'SMA_20D',      ''),
            (    'PV_Ratio',      ''),
            (     'Close_Z',      ''),
            (    'Volume_Z',      ''),
            ('Log_Return_Z',      ''),
            (   'Vol_10D_Z',      ''),
            (   'SMA_20D_Z',      ''),
            (  'PV_Ratio_Z',      ''),
            (   'Signal_Up',      '')],
           names=['Price', 'Ticker'])

In [218]:
# Filter to show only the features ready for model input (Standardized and One Hot Encoding)
final_columns = [
    col for col in data.columns if col[0].endswith("_Z") or col[0].startswith("Signal")
]
print(data[final_columns].head())

Price        Close_Z  Volume_Z Log_Return_Z Vol_10D_Z SMA_20D_Z PV_Ratio_Z  \
Ticker
Date
2024-10-28 -0.583384 -0.129603     0.050311 -2.412794 -0.795787  -0.399718
2024-10-29 -0.565229  3.566613     0.049992 -2.412807 -0.788734  -1.716426
2024-10-30 -0.362985  2.368681     1.304512 -1.400170 -0.766183  -1.488897
2024-10-31 -0.504724  0.728967    -1.039157 -0.997564 -0.752416  -0.975097
2024-11-01 -0.497109 -0.152858    -0.023577 -0.995643 -0.741325  -0.351595

Price      Signal_Up
Ticker
Date
2024-10-28      True
2024-10-29      True
2024-10-30      True
2024-10-31      True
2024-11-01     False

# Question:
## 1. How one hot encoding will behave when the column have 20 uniques values in it
## 2. Repeat everything for gold and silver. Create as many features as you find necessary.
## 3. Can you recreate the pairs trading strategy from last week? Can you do it with different assets (must be correlated)?